### ISSUE TITLE
Introduce --flags as input to begins

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#10] opened 2013-07-31 09:25 UTC
Taking the following mini test.py program:

``` python
@begin.start
def main(debug=False):
    print("Debug is %s" % debug)
```

I would like to be able to:

``` bash
 > python test.py --debug
Debug is True
 > python test.py
Debug is False
```

It seems that this could be achieved through looking at the type of the kwarg "flags".  If the type is "bool", you negate its default value...   

If this were implemented then the following would hold true:

``` python
@begin.start
def main(flipflag=True):
    print("Flip flag is %s" % flagflag)
```

I would like to be able to:

``` bash
 > python test.py --flipflag
Flip flag is False
 > python test.py
Flip flag is True
```

**Comment by aliles** [comment] 2013-08-23 13:00
I agree that `--flag` is aesthetically more pleasing than `--flag=on`, and aesthetics are important. The problem is that support flags requires tracking and special handling these options through multiple layers of the codebase. Each of two attempts at implementing this so far has produced difficult to read and maintain code that may well be obscuring many bugs.

I will leave this issue open for the being while I explore implicit type conversion support in `begin.convert()` for issue #12. If implicit conversion can be made to work and I still can't find a maintainable implementation, it may be better to close this issue unfixed.

We will see.

**Closed as completed** 2013-10-01 12:44 UTC
Labels: enhancement

**Comment by mjdorma** [comment] 2014-02-13 11:00
:100:
